---
title: "Individual2 - Lab3"
author: "Maxwell Farver"
date: "February 19, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Data Cleaning
```{r}
library(tidyverse)
data(happy, package="productplots")
HAPPY <- readRDS("HAPPY.rds")
head(HAPPY)
```

1.)
```{r}
HAPPY[HAPPY=="IAP" | HAPPY=="DK" | HAPPY=="NA"] <- NA
```

2.)
```{r}
HAPPY$AGE[HAPPY$AGE == "89 OR OLDER"] <- 89
HAPPY$AGE <- as.numeric(as.character(HAPPY$AGE))
unique(HAPPY$AGE)
```

3.)
```{r}
HAPPY$AGE <- factor(HAPPY$AGE, levels = c(1:89))
head(HAPPY)
```

Data Exploration
1.)
```{r}
library(ggplot2)
happy2 <- HAPPY[complete.cases(HAPPY[,'HAPPY']), ]
happy2$AGE <- as.numeric(as.character(happy2$AGE))
ggplot(data = happy2, aes(AGE)) + geom_histogram(binwidth = 5)

ggplot(data=happy2, aes(YEAR)) + geom_histogram()
```

2.)
```{r}
# plot 1
ggplot(data=happy2, aes(x=AGE)) + facet_wrap(~HAPPY) + geom_histogram(binwidth = 1)

# plot 2
ggplot(data=happy2, aes(x=DEGREE), stat="count") + 
  facet_wrap(~HAPPY) + geom_bar(mapping = aes(fill=DEGREE)) +
  coord_flip() +
  labs(title = "Happiness Based on Degree Held") +
  theme(plot.title = element_text(size = rel(2)),
        axis.title = element_blank(), 
        axis.ticks = element_blank(),
        axis.text = element_blank())
# plot 3

ggplot(data=happy2, aes(x=FINRELA), stat="count") + 
  facet_wrap(~HAPPY) + geom_bar(mapping = aes(fill=DEGREE)) +
  labs(title = "Happiness Based on Relative Financial Stability") +
  theme(plot.title = element_text(size = rel(1.5)),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 90, size = rel(.75)))
```





